GET http://localhost:3001/

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/10

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name":"Steward Righteous",
    "number":"2547891456665"
}

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name": "Mahaveer"
}

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{
    "name":"arto Hellas",
    "number":"2547891456665"
}